import React from "react"; // import react library to enable jsx rendering
import type { Metadata } from "next"; // import metadata type from next for page metadata typing
import { Inter } from "next/font/google"; // import inter font loader from next for consistent typography
import { ClerkProvider } from "@clerk/nextjs"; // import clerk provider to wrap the app and enable authentication features
import { dark } from "@clerk/themes"; // import dark theme configuration from clerk for consistent dark mode styling

import "../globals.css"; // import global stylesheet to apply global styles across the app

const inter = Inter({ subsets: ["latin"] }); // initialize inter font with latin subset for english character support

export const metadata: Metadata = { // define static metadata object to describe this page in the app
  title: "Auth", // set page title to 'Auth' for browser tab and seo
  description: "Generated by create next app", // set meta description for seo and identification
};

// define root layout component to wrap all pages with shared providers and html structure
export default function RootLayout({
  children, // define children prop representing nested page components
}: {
  children: React.ReactNode; // specify that children is a react node to ensure correct type checking
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark, // apply clerk's dark theme for consistent authentication ui
      }}
    >
      <html lang='en'> {/* define root html element with english language attribute */}
        <body className={`${inter.className} bg-dark-1`}>{children}</body> {/* apply inter font and dark background, then render child components */}
      </html>
    </ClerkProvider>
  );
}
